runtime: custom
service: myappservice
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

runtime_config:
  go_version: go1.16

handlers:
  - url: /.*
    script: auto
